-- 데이터 베이스 이름 생성
-- CREATE DATABASE (DB이름)
-- DEFAULT CHARACTER SET UTF8MB4 DEFAULT COLLATE UTF8MB4_UNICODE_CI;

-- table 생성
CREATE TABLE USER (
	U_IDX	int	NOT NULL auto_increment PRIMARY KEY ,
	USERID	varchar(20)	NOT NULL,
	EMAIL	varchar(30)	NOT NULL,
	PASSWORD	varchar(500)	NOT NULL,
	SALT	varchar(500)	NOT NULL,
	NICKNAME	varchar(20)	NOT NULL,
	IMAGE	varchar(500)
);

CREATE TABLE BOARD (
	B_IDX	int	NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	U_IDX	int	NOT NULL,
	TITLE	varchar(20)	NOT NULL,
	CATEGORY	varchar(20)	NOT NULL,
	CONTENT	text	NOT NULL,
	VIEWCOUNT	int	NOT NULL,
	BREGDATE	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    FOREIGN KEY (U_IDX) REFERENCES USER(U_IDX) on DELETE cascade
);

CREATE TABLE STUDY (
	ST_IDX	int	NOT NULL  AUTO_INCREMENT PRIMARY KEY,
	U_IDX	int	NOT NULL,
	ST_TITLE	varchar(20)	NULL,
	ST_INTRO	varchar(100)	NULL,
	ST_NOW_MEM	int	NULL,
	ST_LIMIT	int	NULL,
	ST_DATE	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ST_FE	INT	,
	ST_BE	INT,
	ST_PUB	INT,
	ST_FULL	INT,
    FOREIGN KEY(U_IDX) REFERENCES USER(U_IDX) on DELETE cascade
);

CREATE TABLE USEDGOODS  (
	UD_IDX	int	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	U_IDX	int	NOT NULL,
	UD_PRICE	int NOT NULL,
	UD_TITLE	varchar(20) NOT NULL,
	UD_CONTENT	text NOT NULL,
	VIEWCOUNT int NOT NULL,
	UD_DATE	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(U_IDX) REFERENCES USER(U_IDX) ON DELETE CASCADE
);

CREATE TABLE CHATTINGROOM (
	R_IDX	int	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	R_NAME	varchar(20)	NOT NULL,
	R_CREATE	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CHATMESSAGE (
	MS_IDX	int	NOT NULL PRIMARY KEY,
	U_IDX	int	NOT NULL,
	R_IDX	int	NOT NULL,
	C_CONTENT	text NOT NULL,
	C_DATE	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(U_IDX) REFERENCES USER(U_IDX),
    FOREIGN KEY(R_IDX) REFERENCES CHATTINGROOM(R_IDX)
);